### ISSUE TITLE
Datepicker config bug

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework#112]
See https://github.com/joomlatools/textman/issues/391#issuecomment-322978725

This also happens in other extensions like docman, e.g. in the category form of docman, the date there doesn’t `autoclose`d when you pick a date where the datepicker helper in the FW has `autoclose` option turned-on by default and was not overridden in the category form view.

**Comment by ercanozkaya** [comment]
Hi @jebbdomingo , pushed a fix to master. Can you please pull & test?

**Comment by jebbdomingo** [comment]
@ercanozkaya I confirm it's working
