### ISSUE TITLE
Vuex requires promise polyfill on IE11

### ISSUE THREAD

**Issue by raeldc** [joomlatools/joomlatools-framework#114]
Client Reported an issue on IE11: 
https://support.joomlatools.com/forums/topic/7964
https://support.joomlatools.com/tickets/topic/8035
https://support.joomlatools.com/tickets/topic/8016
https://support.joomlatools.com/tickets/topic/8018
https://support.joomlatools.com/tickets/topic/8033-internet-explorer-not-displaying-upload-page-properly

![image](https://user-images.githubusercontent.com/66454/29707813-3b368c12-89b9-11e7-95a2-d7c2138716d0.png)

**Comment by raeldc** [comment]
Update: More clients are encountering the error. This time, even in the frontend.

https://support.joomlatools.com/tickets/topic/8016

Same issue as 7964: https://support.joomlatools.com/tickets/topic/8018

@ercanozkaya, now that it affects the frontend, I think we must raise this ticket's priority?

**Comment by johanjanssens** [comment]
@raeldc Yes, @ercanozkaya marked it as prio high, can you please look into this?

**Comment by raeldc** [comment]
Another IE11 issue: https://support.joomlatools.com/tickets/topic/8035

**Comment by ercanozkaya** [comment]
@raeldc Added a fix for the issue and moved the references to the description. Can we merge all support ticket references in the description please?

**Comment by raeldc** [comment]
@ercanozkaya, thanks for the fix. Is it going to be released for 3.1.2? When's it gonna be? What do we tell the customers?

Will put references in the description moving forward.

**Comment by ercanozkaya** [comment]
@raeldc I'm gonna create a beta package and ask for feedback from a few users to confirm the fix. I'll handle that part tomorrow. Then we can do a release on monday with this fix.

**Comment by johanjanssens** [comment]
@ercanozkaya @raeldc What is the status of this ticket?

**Comment by raeldc** [comment]
@johanjanssens this has been released and tested by customers. Unless @ercanozkaya has something to add? I think this ticket can be closed.

**Comment by ercanozkaya** [comment]
This is a v3.1.2 milestone ticket. It was left open it seems. Closing

**Comment by johanjanssens** [comment]
Thanks guys!
