### ISSUE TITLE
Red dot on desktop shouldn't be there

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-framework#115]
The little red dot shouldn't appear in the search field on desktop.

See: https://support.joomlatools.com/tickets/topic/8009-search-icon

## Changed:

- Removed red dot markup from search field
- Updated to latest kui / jui. See changelog: https://github.com/timble/kodekit-ui/releases/tag/v0.2.0

**Comment by robinpoort** [comment]
@ercanozkaya I removed the markup and updated to the latest KUI / JUI. See description for kui changelog. Most things in KUI are "new" and the rest are mostly small improvements. Everything should stay working as expected but you might want to click a bit through the extensions as well to see if nothing weird pops up

**Comment by ercanozkaya** [comment]
@robinpoort can you please fix the following issue one before we merge this in:
https://github.com/timble/kodekit-ui/issues/30
