### ISSUE TITLE
Forcing Joomla template to "system" breaks overrides

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#117]
We force Joomla template name to be `system` if X-Flush-Response header is set. This lets us control the page contents 100%

However, this breaks the template overrides for the form layouts in Docman frontend. 

See: https://support.joomlatools.com/tickets/topic/8501
See: https://support.joomlatools.com/tickets/topic/8720
See: https://support.joomlatools.com/tickets/topic/8713-hide-permissions-and-featured-image-on-uploading-files-or-creating-new-categories
See: https://support.joomlatools.com/tickets/topic/9350

Related ticket: #145

**Comment by johanjanssens** [comment]
To resolve this: use the implementation to find the template override path that is part of the file locator: see: https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/component/koowa/template/locator/file.php#L45

**Comment by amazeika** [comment]
See related ticket: #145

**Comment by johanjanssens** [comment]
@ercanozkaya Can still add this, to remain BC we could add two levels of fallbacks, one to the active template and one to system. That would allow current system overrides to continue working?
