### ISSUE TITLE
Modulable approach for loading JS dependencies

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework#122]
Allow our JS dependencies to be loaded async or outside the head section without breaking. We rely on DOM ready events for using our dependencies, this is an assumption that doesn't hold when loading JS async.

#### Support tickets

* https://support.joomlatools.com/tickets/topic/8203-problematic-javascript-code-order-in-koowa-js

**Comment by johanjanssens** [comment]
@amazeika @ercanozkaya I suggest to close this issue. In modern browser there is not need anymore to put js at the bottom of the page, either use async or defer influence have javascript is loaded. If you rely on dom ready you should use defer to load the js.

**Comment by amazeika** [comment]
@johanjanssens @ercanozkaya We haven't ran into more requests such as these. The main problem here was that this guy was working on some kind of optimization script and that the fact that we are currently relying on the domready event to avoid depending on JS loading order. His plugin required that our JS is loaded in order, something we don't care about much.

His point is that there are optimizers that will grab the JS and then load it async and in this case the order will matter. He pointed out also that another means to avoid this is to use a JS module loader to load our JS.

Again, we haven't had more issues regarding this way of proceeding, so I guess we can close this or improve our JS loading mechanism.

@ercanozkaya what are your thoughts mate?

**Comment by johanjanssens** [comment]
@amazeika @ercanozkaya Marking this as invalid then.  As discussed all javascript should be loaded from head and use defer or async depending on how it should be loaded. If IE11 is no longer a compat requirement we can also start making use of modules.
