### ISSUE TITLE
Tree indent issue

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-framework#124]
Indentation of menu items without children on first level is sub-optimal. Keep indentation the same as for items with children.

![tree-indent](https://user-images.githubusercontent.com/4848082/32785501-006932d2-c952-11e7-9cd1-10e8e347cbcc.png)

**Comment by johanjanssens** [comment]
@robinpoort Thanks for handling this one. Customer will be happy. Small note. In future try to do a PR for everything, this makes it easier to assign and review changes. We are using this as our default flow.

**Comment by ercanozkaya** [comment]
Moving to ready.
