### ISSUE TITLE
Incompatible Declaration of KControllerToolbarCommand::count()

### ISSUE THREAD

**Issue by raeldc** [joomlatools/joomlatools-framework#126]
As client reported, turning on Maximum Error reporting on DOCman will throw this error:

```
Fatal error: Declaration of KControllerToolbarCommand::count() must be compatible with KObjectConfig::count($mode = COUNT_NORMAL) in 
.../public_html/libraries/joomlatools/library/controller/toolbar/command/command.php on line 16
```

#### Support tickets

* https://support.joomlatools.com/tickets/topic/8389
* https://support.joomlatools.com/tickets/topic/8465

**Comment by ercanozkaya** [comment]
Merged to master and synced to Kodekit

**Comment by mgofvit** [comment]
can we have the solution?
