### ISSUE TITLE
Improve https detection

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#144]
See: https://support.joomlatools.com/tickets/topic/8630
See: https://support.joomlatools.com/tickets/topic/9901

In this case the proxy server is giving conflicting information it's requesting http over port 443, while it actually want's https over port 443. 

### Proposed solution

Override the isSecure() method to check if port is 443 or proto is https, assume proxy servers wants a default secure connection if either is the case.

See: https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/library/dispatcher/request/abstract.php#L982

**Comment by idealadarsh786** [comment]
You could try URL :443/ which would hopefully force HTTP traffic over port 443.

However, you might find if your proxy is set up[ to only allow port 443, it also only allows HTTPS traffic in which case the above would not work.

**Comment by ercanozkaya** [comment]
See #271
