### ISSUE TITLE
Do not flush the stream if the response is not streamable

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#15]
See: https://github.com/timble/kodekit/issues/93

See: https://support.joomlatools.com/forums/topic/6705-bulk-import-files-folders#comment-36948

**Comment by johanjanssens** [comment]
@ercanozkaya We need to open this up again, this change is creating issues with large files. See: 
https://support.joomlatools.com/forums/topic/6705#comment-36067

From @amazeika: I’ve checked the code and we load the whole video on memory before streaming (first response sent back to client). He’s getting a mem error as a consequence (his videos are big). We need a better approach here. Instead of echoing $response->getStream()->toString() on transport we could progressively read the stream in chunks to avoid the memory error.

**Comment by johanjanssens** [comment]
Note, reverted these changes on a users site and the streaming worked as expected.

**Comment by johanjanssens** [comment]
@ercanozkaya Customer has confirmed that rolling back this changes fixes his issue. This is a high prio issue, anyone with not enough memory will not be able to download large file with DOCman and FILEman has another report about this today. Can we roll out fw release and DOCman and FILEman maintenance releases?

**Comment by ercanozkaya** [comment]
@johanjanssens Let's do it together with Textman. Fileman needs a release anyway, for Docman it would be a repackage. Did you rollback the commits already?

**Comment by johanjanssens** [comment]
@ercanozkaya Agreed, haven't rolled back yet. You wanna handle that?

**Comment by ercanozkaya** [comment]
@johanjanssens you mind handling this? I'm not 100% certain on what needs to happen where.

**Comment by johanjanssens** [comment]
@ercanozkaya @amazeika This issue was not fixed for 2.1, and i creating issues for customers. We need to release a new update to fix this asap, or we will have more customers with large files that have download issues.

Related tickets: 

- https://support.joomlatools.com/tickets/topic/8615
- https://support.joomlatools.com/tickets/topic/8587

**Comment by amazeika** [comment]
@johanjanssens Instead I would perhaps encourage people to upgrade. Let me explain my point of view. There aren't really that many reports of this issue, which is a bug, I agree. However,  I've seen this like 3 times at most, including the reports were this issue was spotted, I've debugged this myself. We have fixed this for 3.0 and DOCman is already at 3.2. People need to upgrade, 2.1 is legacy and may contain bugs.

Thoughts?

**Comment by johanjanssens** [comment]
Cannot do that. The problem is that this change made itself into 2.1.6, it was there in 2.1.5. We urged people to install a security release, we got a lot of re-subscribes, these people are not interested to upgrade Joomla to run DOCman 3.2. They want a secure site. Their downloads are now breaking, after a security upgrade.

We really need to fix this asap.

**Comment by amazeika** [comment]
@johanjanssens understand. Who's gonna work on this?

**Comment by johanjanssens** [comment]
Ercan is gonna handle this one.
