### ISSUE TITLE
Allow decoration of JSON views

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework#155]
JSON views provide a string when the view gets rendered. It would be interesting to see if we could delay the JSON encoding until the response gets sent. This would allow for view decoration of the JSON data, useful when making forward calls within the dispatcher.

Notes: 

1. Improve the serialisation of entities to json by implementing the jsonSerialize() interface. See: https://github.com/joomlatools/joomlatools-pages/commit/a473a55739321335a02937641f6db37730cfa674 and https://github.com/joomlatools/joomlatools-pages/commit/9c5dc02dd0a96666507c93fd2d9ace470c33902d

**Comment by johanjanssens** [comment]
@amazeika This could be possible, i have been considering to pass the view back as an object and not a string. That way it can be interacted with in the pipeline, the response would then be responsible to handle it.

**Comment by johanjanssens** [comment]
I will see if i can work on this and make it BC.
