### ISSUE TITLE
Update to Kodekit UI v1.0.3 to fix CK editor source view

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-framework#162]
#### Steps to reproduce the behavior

1. Open up TEXTman and edit an article
2. In the ck editor click on the source icon to open up source view
3. Only 1 line is visible and you get a very small scrollbar

#### Testing instructions

1. Pull master
2. check the ck editor source view

**Comment by johanjanssens** [comment]
@amazeika @ercanozkaya Can you guys check this one so we can get it resolved?

**Comment by ercanozkaya** [comment]
Seems this was fixed already.

**Comment by amazeika** [comment]
Looks fixed indeed.
