### ISSUE TITLE
Document ordering icon issue

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#166]
@ercanozkaya commented on [Wed Jun 20 2018](https://github.com/joomlatools/docman/issues/1238)

Please describe the expected and actual behavior.

#### Steps to reproduce the behavior

1. Go to Docman backend
2. Order by ordering column
1. Hover over a positioner
1. You will see a forbidden mouse icon

#### Testing instructions

1. - [ ] _
2. - [ ] _

#### Support tickets

* https://support.joomlatools.com/tickets/topic/8968

---

@ercanozkaya commented on [Wed Jun 20 2018](https://github.com/joomlatools/docman/issues/1238#issuecomment-398737796)

@robinpoort  need some help here. The HTML hasn't changed but the ordering k-positioner span is always showing a forbidden icon on hover. Could you check if this is something that happened in the latest UI changes? This only happens in the latest releases.

**Comment by robinpoort** [comment]
@ercanozkaya pushed in `feature/#166-document-ordering`
