### ISSUE TITLE
Add `k-no-css-errors` to `k-ui-container`

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-framework#168]
It would be great to add the `k-no-css-errors` class to the `k-ui-container` on building a new version of our extensions. Right now a client could get the error that is intended for developers as soon as:
- they start customizing the backend
- they are using another template than our default one?
- a view slipped through testing and our product actually has the error there (in a modal for example)

#### Support tickets

* https://support.joomlatools.com/tickets/topic/8996-k-ui-container#comment-49176

**Comment by ercanozkaya** [comment]
@robinpoort can we solve this when compressing the CSS file with Grunt? That would remove the definition of the class for the min file

**Comment by robinpoort** [comment]
if you could change the name of the class on compressing that be great. Is that possible?

**Comment by johanjanssens** [comment]
@robinpoort @ercanozkaya Can we get this issue resolved so we can included it in the next framework build?

**Comment by ercanozkaya** [comment]
@johanjanssens This has been merged already. Pipeline was wrong
