### ISSUE TITLE
Set default charset for MySQLi Connection

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#178]
Some MySQLi connections do not set the charset to utf8 which results in invalid encoding. 

http://php.net/manual/change.php?page=en%2Fmysqli.set-charset.php

#### Steps to reproduce the behavior

1. see joomlatools/textman#488 and joomlatools/textman#667

#### Testing instructions

1. - [ ] _
2. - [ ] _

#### Support tickets

* https://support.joomlatools.com/tickets/topic/9005
* https://support.joomlatools.com/tickets/topic/8564

**Comment by johanjanssens** [comment]
@ercanozkaya Was this the issue that the customer had and the fix he confirmed?

**Comment by ercanozkaya** [comment]
Yes, there is still a chance this might break charsets another esoteric setup but we will have to take our chances and roll out to see it. Going with Textman first should be safer as we test it with fewer installs.
