### ISSUE TITLE
Bug in Decorator

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework#19]
`Catchable fatal error: Argument 2 passed to KCommandHandlerAbstract::execute() must implement interface KCommandChainInterface, none given, called in /home/vagrant/Projects/joomlatools-framework/code/libraries/joomlatools/library/controller/toolbar/decorator.php on line 34 and defined in /home/vagrant/Projects/joomlatools-framework/code/libraries/joomlatools/library/command/handler/abstract.php on line 65`

`KControllerToolbarDecorator` doesn't pass the required parameter `$chain` ([see](https://github.com/joomlatools/joomlatools-framework/blob/894dc01c197fdb6d8eb3757032d56fba8aa7db25/code/libraries/joomlatools/library/controller/toolbar/decorator.php#L34)) though `KCommandHandlerAbstract` doesn't use the 2nd argument `$chain` ([see](https://github.com/joomlatools/joomlatools-framework/blob/894dc01c197fdb6d8eb3757032d56fba8aa7db25/code/libraries/joomlatools/library/command/handler/abstract.php#L65))

**Comment by johanjanssens** [comment]
@ercanozkaya  Can you review this for @jebbdomingo ?

**Comment by johanjanssens** [comment]
@ercanozkaya Can you check if this needs merging in Kodekit?

**Comment by ercanozkaya** [comment]
@johanjanssens merged to Kodekit
