### ISSUE TITLE
Update to latest KUI JS

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-framework#204]
The CSS is already updated in https://github.com/joomlatools/joomlatools-framework/issues/203

Running `grunt` in this repository however triggers JS compiles which break some stuff in our extensions.

Already discovered:
- We need to make sure kui-initialize.js is loaded between modernizr.js and jquery.js
- Saving a new document will give us an "add" error (probably for the Vue application). It does save the document but just loads a new add document form telling you that add failed.

There might be other small hickups as well. I suggest checking the changes made in KUI and test those changes in our extensions.

**Comment by robinpoort** [comment]
@ercanozkaya I added the changes as requested. Note that saving a new document gives a false error warning while adding a new category doesn't. Haven't tested anything else in other extensions.

**Comment by johanjanssens** [comment]
@ercanozkaya What is the status of this one?

**Comment by ercanozkaya** [comment]
Forgot to close it. Done now
