### ISSUE TITLE
Add deselect support to optionlist

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#22]
Prompt entires for select boxes are now scattered all over the place. optionlist supports it for only select2 at the moment. 

Make the support universal by automatically adding the prompt entry to the options list.

**Comment by ercanozkaya** [comment]
Note: needs to be merged into Kodekit

**Comment by amazeika** [comment]
@ercanozkaya Re-opened as requested. All yours to port to Kodekit.

**Comment by ercanozkaya** [comment]
Ported to kodekit as well.
