### ISSUE TITLE
Content length issue with decoratable

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#237]
We used to have a special transport for Joomla which did not set all the headers. Now however, HTTP transport sends the response indifferent to the current decorator. 

This means Content-Length header is set to the size of the content Koowa returns. Since Joomla wraps around this the actual content length is a mismatch and the browser gets only gets a partial response. 

Two proposed solutions: 
- `header_remove('Content-Length')` in decoratable since this is the only problematic header.
- Bring back a special Joomla response transport

**Comment by ercanozkaya** [comment]
@johanjanssens This is blowing up the page render on nginx. Thoughts on a solution?

**Comment by johanjanssens** [comment]
@ercanozkaya  Didn't considered the content-lenght issue indeed I wouldn't bring back to the Joomla response transport, header_remove should do the trick just fine.
