### ISSUE TITLE
Allow passing additional JavaScript options to Select2

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#29]
Right now you cannot add custom JavaScript code to select2 calls. Add a function wrapper around the call so that custom options can be added. Example:

Calling select2 by:
```
<?= helper('listbox.users', array(
     'options_callback' => 'callbackSetDropdownParent'
))?>
```
 
results in:

```
$('.foo').select2(callbackSetDropdownParent(options));
```

Then ``callbackSetDropdownParent`` can be defined anywhere.

**Comment by johanjanssens** [comment]
@ercanozkaya Should this be synced with Kodekit?
