### ISSUE TITLE
Unable to disable an exception handler

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework#33]
`KExceptionHandlerAbstract->removeExceptionCallback()` doesn't remove the callback effectively, it seems `array_search()` is best used with a string rather than an object.

See: https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/library/exception/handler/abstract.php#L229

**Comment by ercanozkaya** [comment]
@johanjanssens Can you review please?

This works now:
```

$m = KObjectManager::getInstance()->getObject('exception.handler');

$a = function() {};
$m->addExceptionCallback($a);

$f = $m->getExceptionCallbacks()[0];
$m->removeExceptionCallback($f);

var_dump($m->getExceptionCallbacks());
$m->removeExceptionCallback($a);

var_dump($m->getExceptionCallbacks());
```
