### ISSUE TITLE
PHP 7.4 fixes

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#336]
PHP 7.4 deprecates a bunch of functions. Ensure everything is working well on it.

#### Support tickets

* https://support.joomlatools.com/tickets/topic/10613
* https://support.joomlatools.com/tickets/topic/10643
- https://support.joomlatools.com/tickets/topic/10653
- https://support.joomlatools.com/tickets/topic/10647
- https://support.joomlatools.com/tickets/topic/10648

**Comment by johanjanssens** [comment]
@ercanozkaya More reports by customers:

- https://support.joomlatools.com/tickets/topic/10653-docman-modules-are-not-displaying-on-the-frontend-and-i-m-getting-a-backend-error-message#comment-57284

-

**Comment by johanjanssens** [comment]
@ercanozkaya Received one more report today: https://support.joomlatools.com/tickets/topic/10648
