### ISSUE TITLE
Cacheable error

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework#35]
Template object cannot be casted to string

https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/component/koowa/controller/behavior/cacheable.php#L118

![image](https://cloud.githubusercontent.com/assets/5572579/18049283/d7a9c418-6e19-11e6-93d5-f0907723693c.png)

Use `$data['component'] = $view->getTemplate()->getIdentifier();` instead

**Comment by johanjanssens** [comment]
@ercanozkaya Can you investigate this?

**Comment by ercanozkaya** [comment]
@johanjanssens I don't think we can do this anymore. What we need access to is the unfiltered view data in _afterRender. However KTemplate::render is already called at that point and it modifies the source in place: https://github.com/joomlatools/joomlatools-framework/blob/05dc41633aff936a5cf78b52a89bcb7c2a7041f2/code/libraries/joomlatools/library/template/template.php#L187-L187

So we cannot access the raw source anymore. Two ways we can handle this: 

* We can cache filtered data but this will only work for static views.
* We can drop HTML view caching from cacheable, as we don't use it anywhere. com_files uses cacheable as a JSON store and that is all. Thoughts?

**Comment by johanjanssens** [comment]
@ercanozkaya Being able to cache on a controller/dispatcher level would allow us to speed things up considerably. This is one of the reasons we have the layered architecture in place. 

We don't need to cache the unfiltered output, we can cache the filtered output, be it only in an anonymous state. When a user is logged in this would be harder. 

Are we caching a per request basis anywhere else? If not, i would still look into improving this cache.

**Comment by ercanozkaya** [comment]
@johanjanssens No we don't use template caching anywhere else. By the way anonymous users still have tokens in the frontend forms so caching them would be a no-go as well right?

**Comment by johanjanssens** [comment]
@ercanozkaya Tokens for CSRF protection? It could be we still generate those, we don't need them though. If we refactor that out we could easily cache stuff for anonymous users?

**Comment by ercanozkaya** [comment]
@johanjanssens I made caching work now with the latest KTemplate changes so it is again plug&play. Non-static content might still be an issue but that is a topic for another ticket IMHO. can you review the PR please?
