### ISSUE TITLE
Disable Content-Length for non-downloadable requests

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#366]
We are seeing misconfigured servers messing with encoding which renders our own Content-Length value obsolete. However the server is not removing the header. And result is page is only partially displayed.

Instead, only send Content-length for downloads and streaming requests

#### Support tickets

* https://secure.helpscout.net/conversation/1108181470/8196/

**Comment by johanjanssens** [comment]
@ercanozkaya In https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/component/koowa/dispatcher/behavior/decoratable.php#L98 we are creating an override for the content-length. With the changes you made this code can be removed
