### ISSUE TITLE
Do not check if response is streamable to determine if it's cacheable

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#37]
The check for isStreamable() in the isCacheable() method of KDispatcherResponseAbstract will lead to the response not being cacheable in most cases, only when the response is not streamable it can be cacheable. 

Solution: Remove the check. If this check is required it should be done in the implementing code not in the framework. 

See: https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/library/dispatcher/response/abstract.php#L244

**Comment by ercanozkaya** [comment]
@johanjanssens What are the implications of removing this? As far as I see, we provide `private', 'must-revalidate` by default which has very minimal effect on caching anyway so we can just remove this it seems?

**Comment by johanjanssens** [comment]
@ercanozkaya This will not have implications for the default use. What it solves is that if you are using chunked encoding or streaming you should be able to set a response as cacheable so the browser can cache it.

This code prevents any kind of caching with chunked and or range serving.

**Comment by ercanozkaya** [comment]
@johanjanssens In that case I'm gonna go ahead and do the removal in the description?

**Comment by johanjanssens** [comment]
@ercanozkaya Yep. The default should be that the code doesn't prevent caching at all. If caching needs to be prevents the implementing code can enforce this.

**Comment by ercanozkaya** [comment]
Removed the code, looks like it was already like this in Kodekit

**Comment by johanjanssens** [comment]
Likely i fixed that already indeed.
