### ISSUE TITLE
Joomla 4 compatability issues

### ISSUE THREAD

**Issue by YoKoGFX** [joomlatools/joomlatools-framework#389]
I already looked into the compatability with J4, as I try to test a extension that we modified.

From what I can see is that this:

JFactory::getApplication()->getCfg
needs to be updated to this:
JFactory::getConfig()->get

also the JEventDispatcher, JApplication::stringURLSafe and the 'attributes' => $user->getParameters()->toArray() is deprecated. From what I can see these are the biggest issues.

**Comment by johanjanssens** [comment]
@YoKoGFX Thanks. We have started prepping to provide compatibility for Joomla 4 in the framework. If you have more feedback please let us know, makes our work a little bit easier.

**Comment by ercanozkaya** [comment]
Hi @YoKoGFX, thanks for the report. We have started work on Joomla 4 compatibility and we are getting close to a beta release. 

If you would like to test it out early, you can use the feature/389-j4 branch: https://github.com/joomlatools/joomlatools-framework/tree/feature/389-j4 or you can use the PR at #406
