### ISSUE TITLE
Cache issue

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework#413]
Several JT extensions are affected by this issue.

#### Steps to reproduce the behavior

1. Install LOGman and DOCman
1. Go LOGman > Activities
1. Login on the frontend or just enable `Log activities from guest users` in the LOGman settings
1. Download some files
1. Go LOGman > Activities again

**Result:** Still empty

1. Refresh the page `Command + R`

**Result:** Displays the download activities

This also affects the DOCman Limit plugin, see https://github.com/joomlatools/docman-limit/issues/9

**Screencast**
https://drive.google.com/file/d/1aT5IRXvpvVBPGLvf8rZK_hk7NW46AoJj/view

**Comment by yiendos** [comment]
@jebbdomingo can't access the screencast in the above description, `No preview available, File is in owner's trash`

**Comment by jebbdomingo** [comment]
> @jebbdomingo can't access the screencast in the above description, `No preview available, File is in owner's trash`

@yiendos I updated the link
