### ISSUE TITLE
Site UI

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-framework#44]
Implement the site UI from kodekit-ui

- [ ] Create all views for DOCman to style UI (I think I'm at 80% now)
- [ ] Add the needed JS and make a site.js file
- [ ] Namespace refactor
- [ ] Create a styleguide like the admin one so we can make branches of our extensions and build all the views
- [ ] Test a bit
- [ ] Refactor both site and admin

**Comment by johanjanssens** [comment]
@robinpoort @ercanozkaya What is the status of this one?

**Comment by robinpoort** [comment]
@johanjanssens Slow but steady. Starting to look good! Will continue after my holiday.

What needs to be done for a first version:
- [ ] Create all views for DOCman to style UI (I think I'm at 80% now)
- [ ] Add the needed JS and make a site.js file
- [ ] Namespace refactor
- [ ] Create a styleguide like the admin one so we can make branches of our extensions and build all the views
- [ ] Test a bit
- [ ] Refactor both site and admin

**Comment by johanjanssens** [comment]
@robinpoort Ofcourse. This belongs into the 3.0 milestone right?

**Comment by robinpoort** [comment]
@johanjanssens Don't know when 3.0's "due" but it's still quite some work

**Comment by johanjanssens** [comment]
Well it's done. So 3.1 it is :)

**Comment by johanjanssens** [comment]
@ercanozkaya Do you agree we close this and mark it invalid?

**Comment by ercanozkaya** [comment]
@johanjanssens yes agreed.
