### ISSUE TITLE
Improve LOGman handling during installs

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework#45]
Now that the framework takes care of upgrading reusable components, LOGman must be always disabled when upgrading Activities.

This will ensure that no errors are thrown due to API differences between LOGman and Activities.

LOGman will then enable itself when upgraded.

**Comment by amazeika** [comment]
Made priority to high to make sure we get this done before the next release takes place

**Comment by ercanozkaya** [comment]
@amazeika Have yo worked on this? Or should we work on this?

**Comment by amazeika** [comment]
@ercanozkaya You can take it, thx.

**Comment by johanjanssens** [comment]
@amazeika @ercanozkaya What is the status of this one?

**Comment by amazeika** [comment]
@johanjanssens This is ready, marking as closed.

**Comment by amazeika** [comment]
Duplicate, see #308
