### ISSUE TITLE
Add HTTP_ORIGIN to check for CSRF

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#46]
See: https://support.joomlatools.com/forums/topic/6964
See: https://support.joomlatools.com/forums/topic/7009
See: https://support.joomlatools.com/forums/topic/7038
See: https://support.joomlatools.com/forums/topic/7230

If PHP is configured to run byhind a proxy the HTTP_REFERER header might not be available which leads to during POST requests. To reoslve this add HTTP_ORIGIN header to mitigate CSRF attacks.

More info see: https://www.owasp.org/index.php/CSRF_Prevention_Cheat_Sheet#Standard_Header_Checks

Related: https://github.com/joomlatools/archive-joomlatools-framework/issues/261

**Comment by ercanozkaya** [comment]
This is being fixed in #71. Closing this one.
