### ISSUE TITLE
Improve logic when adding Stream Filters

### ISSUE THREAD

**Issue by raeldc** [joomlatools/joomlatools-framework#48]
When adding a stream filter, there is a check if the filter name is in the list returned by `stream_get_filters()`. 

https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/library/filesystem/stream/abstract.php#L813

However, `stream_get_filters()` returns filter group strings like `mcrypt.*`. So if you try to add something specific like `mcrypt.decrypt`, it will be ignored.

The logic needs to be improved. One approach is to get the filter group from the filter name, then check `stream_get_filters()` if `filtergroup.*` is included.

**Comment by johanjanssens** [comment]
@raeldc Can you link this to the specific ticket for DOCman Encrypt so we understand the references?

**Comment by raeldc** [comment]
The related ticket is:

https://github.com/joomlatools/docman-encrypt/issues/8

Although this bug shouldn't stop us from proceeding. We could simply implement a filter object instead of using PHP's mcrypt stream filter.

**Comment by ercanozkaya** [comment]
@raeldc From what I understand you are trying to do something like `$stream->addFilter('mcrypt.decrypt');` is that right?

If so, the first block won't be able to create the filter as that is not a valid identifier. But the second one here will run adding the filter: 
https://github.com/joomlatools/joomlatools-framework/blob/05dc41633aff936a5cf78b52a89bcb7c2a7041f2/code/libraries/joomlatools/library/filesystem/stream/abstract.php#L840-L840

Am I missing something?
/cc @johanjanssens

**Comment by raeldc** [comment]
@ercanozkaya,

I might have forgotten to update you about this ticket. The problem that we were having is not related to this one. It's more related to headers and content-length which we have already solved. We might have rushed into pointing this as the problem since we had limited time figuring it out without really understanding how it worked. 

We can close this as `invalid`.

**Comment by ercanozkaya** [comment]
@raeldc Thanks for the explanation! Closing as invalid
