### ISSUE TITLE
UI wrapper class refactor

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#49]
- [x] Add Joomla page suffix class to the wrapper in ComKoowaTemplateHelperUi
- [x] Rename `koowa` to `k-ui-namespace` 
- [x] Make sure `k-ui-namespace` can be used on any element.
- [x] Rename `koowa-container` to `k-ui-container`

See: https://support.joomlatools.com/forums/topic/6689#comment-35918

**Comment by robinpoort** [comment]
@ercanozkaya I did the work in branches in the repositories you can see referenced above.

I didn't touch joomlatools-todo yet. We can do that in one go when finishing up the UI there. See: https://github.com/joomlatools/joomlatools-todo/issues/11

I've looked through the entire codebase and changed every koowa instance I was sure of that it'd was there for the namespace purpose. I think it'd be wise if you could thoroughly look through the changes and check the repositories to see if I missed stuff.

I wasn't sure about the following koowa instances:

- joomlatools-framework/autoload.php:36
- joomlatools-framework/code/libraries/joomlatools/component/koowa/dispatcher/response/transport/http.php:34
- joomlatools-framework/code/libraries/joomlatools/component/koowa/dispatcher/response/transport/http.php:38
- joomlatools-framework/code/libraries/joomlatools/component/koowa/template/filter/version.php:97
- joomlatools-framework/code/libraries/joomlatools/library/class/registry/cache.php:23
- joomlatools-framework/code/libraries/joomlatools/library/filesystem/stream/factory.php:60
- joomlatools-framework/code/libraries/joomlatools/library/object/locator/abstract.php:70
- joomlatools-framework/code/libraries/joomlatools/library/object/manager/manager.php:104
- joomlatools-framework/code/libraries/joomlatools/library/object/registry/cache.php:23
- joomlatools-framework/code/libraries/joomlatools/library/template/cache.php:23
- joomlatools-framework/code/libraries/joomlatools/library/template/template.php:88
- joomlatools-framework/code/libraries/joomlatools/library/user/session/abstract.php:136
- joomlatools-framework/code/plugins/system/joomlatools/joomlatools.php:123
