### ISSUE TITLE
3.5.0 broke support for calling JSON over URL?

### ISSUE THREAD

**Issue by YoKoGFX** [joomlatools/joomlatools-framework#497]
On our website we use fullcalendar. The latest update of the framework  broke the support to call JSON over URL. I cannot see what could have broken this in the update.

#### Steps to reproduce the behavior

We currently use Joomlatools Framework 3.4.13 and fullcalendar 5.7.0.

this is the call we do inside the fullcalendar to call the events:
`/index.php?option=com_ourcomponent&view=events&format=json&type=calendar&page_id=12345&address_format=4
`

before the update it displayed a JSON, now the URL it simply is empty. We can reproduce this and every time it breaks with the update to 3.5.0 all versions before work without any problem!

**Comment by johanjanssens** [comment]
@YoKoGFX For the fix see: https://github.com/joomlatools/joomlatools-framework/issues/480 or wait for the next release. The white page you are experiencing is also a regression issue it has been fixed here: https://github.com/joomlatools/joomlatools-framework/issues/495

In future please do not use the Github issues for reporting issues or asking questions. We don't have discussions enabled for this repo but feel to to contact us here: https://github.com/joomlatools/joomlatools-pages/discussions
