### ISSUE TITLE
Use  Koowa::isDebug check for debugging

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#534]
* Add Koowa::isDebug and Koowa::setDebug methods 
* Use Koowa::isDebug instead of xdebug check so that we are sure that only we enable the full on debug experience on framework.

#### Support tickets

* https://support.joomlatools.com/tickets/topic/12116

**Comment by amazeika** [comment]
@ercanozkaya Please review these 3 last changes I've made. This normally fixes the debugger and error handling issues we've discussed today on slack. This now works well on both Joomla 3 and 4.

**Comment by johanjanssens** [comment]
@amazeika Did review, and made two smaller changes myself for code that i introduced we don't need. Took it out again.

**Comment by johanjanssens** [comment]
@ercanozkaya I have removed KOOWA_DEBUG, this change will need to be synced with Kodekit, some of the other changes @amazeika has made also need syncing.

**Comment by johanjanssens** [comment]
Reverted last change again, after discussion with Ercan
