### ISSUE TITLE
Blacklist scripts on document template filter

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework#547]
This particular filter https://github.com/joomlatools/joomlatools-framework/blob/master/code/libraries/joomlatools/component/koowa/template/filter/document.php gets pushed when rendering editors on our forms. It ensures that the current selected editor has all the assets loaded to properly fonction on our forms. 

A big problem with the approach is that this will also push any script that got previously added by a system plugin (see issue on support ticket below).

A proper solution for this problem would be to implement some kind of blacklist which would be used by the template filter to avoid pushing some known scripts that cause problems.

We could hardcode some of these in the template filter and/or make use of the /joomlatools-config/docman.php configuration file to push more scripts on the customer site directly.

#### Support tickets

* _ https://secure.helpscout.net/conversation/1677199783/12482/

**Comment by amazeika** [comment]
@jebbdomingo I have assigned you the ticket. We have discussed the issue in question here => https://timble.slack.com/archives/C01CA7W75DG/p1635928115000600

Regarding the exact approach I would suggest that you consult this with @johanjanssens. What I've put above is a suggestion on how to approach it.

Please let me know if you need help with this.

**Comment by johanjanssens** [comment]
@jebbdomingo Can you please re-open this, remove the release you created? I will update the code, this is a bit too hackish for being framework quality code.  The config option should be properly named and the integration should be able to handle both scripts and stylesheets and probably also other includes

**Comment by johanjanssens** [comment]
Reached out, no reply from customer.
