### ISSUE TITLE
Uncaught Error: mysqli object is already closed / PHP8 MySQL8

### ISSUE THREAD

**Issue by anibalsanchez** [joomlatools/joomlatools-framework#554]
Please describe the expected and actual behavior.

#### Steps to reproduce the behavior

On a site with PHP8 MySQL8, I'm getting this error:

```sh
[19-Nov-2021 09:17:08 UTC] PHP Fatal error:  Uncaught Error: mysqli object is already closed in ..../public/libraries/joomlatools/library/database/adapter/mysqli.php:174
Stack trace:
#0 ..../public/libraries/joomlatools/library/database/adapter/mysqli.php(174): mysqli->ping()
#1 ..../public/libraries/joomlatools/library/database/adapter/mysqli.php(157): KDatabaseAdapterMysqli->isConnected()
#2 ..../public/libraries/joomlatools/library/database/adapter/abstract.php(124): KDatabaseAdapterMysqli->disconnect()
#3 [internal function]: KDatabaseAdapterAbstract->__destruct() 
#4 {main}
  thrown in ..../public/libraries/joomlatools/library/database/adapter/mysqli.php on line 174 
```

#### Testing instructions

Nothing special. The site has been running perfectly fine, but when I change to PHP 8 I get the error. The latest v3.5.7 library is installed. Joomla is updated to the latest 3.10.3. MySql 8.0.27-0ubuntu0.20.04.1 and PHP 8.0.12

#### Support tickets

I haven't opened a ticket.

#### Workaround

```php
    /**
     * Check if the connection is active
     *
     * @return boolean
     */
    public function isConnected()
    {
        try {
            // FIX: PHP Fatal error:  Uncaught Error: mysqli object is already closed
            return ($this->_connection instanceof MySQLi) && @$this->_connection->ping();
        } catch (Exception $e) {
            return false;
        }
    }
```

See: https://support.joomlatools.com/tickets/topic/12116

**Comment by johanjanssens** [comment]
@anibalsanchez Thanks, we are investigating the issue to see how to best fix this.

**Comment by ercanozkaya** [comment]
@anibalsanchez Thanks for the detailed report and the proposed fix! We are incorporating this into the next release.
