### ISSUE TITLE
Clearing multi-select filter not working

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework#561]
See https://github.com/joomlatools/docman/issues/1556

#### Steps to reproduce the behavior

1. Install DOCman master on Joomla 4 
[com_docman_v4.0.1.zip](https://github.com/joomlatools/docman/files/7641006/com_docman_v4.0.1.zip)
2. Create some documents with tags
3. In documents listing, filter by Tags in the scopebar, click `Apply filter`
4. Clear the `Tags` filter

**Current result:** The tags filter isn't cleared

#### Package
[com_docman_v4.0.1.zip](https://github.com/joomlatools/docman/files/7641012/com_docman_v4.0.1.zip)

#### Support tickets

* https://support.joomlatools.com/tickets/topic/11004

**Comment by yiendos** [comment]
@jebbdomingo installing 4.0.0-master show the tag issue in operation, installing the proposed fix works like a dream. Good to go!
