### ISSUE TITLE
Form validation error keeps displaying multiple times

### ISSUE THREAD

**Issue by allanpilarca** [joomlatools/joomlatools-framework#59]
When trying to validate a form the error keeps displaying multiple times. I encountered this in DOCman Leads plugin and i also tried this in docman's demo page: https://demo.joomlatools.com/joomla3/en/docman/submit-document

To recreate this error these are the steps:
1. Submit the form without inputing any value
2. Move your cursor in the "Title" input field
3. Move your cursor out of the "Title" input field

The error messages keeps displaying everytime you focus-out of the input field even there is already an error message on that field.

Please see the attached gif for the demo:
![docman submit document - validation](https://cloud.githubusercontent.com/assets/194313/21041526/882b7cc6-be26-11e6-9550-cb6febaf2f9f.gif)

**Comment by ercanozkaya** [comment]
Hi @allanpilarca Just pushed a fix to the feature/59-validation branch. Could you please test it both frontend and backend? Then we can merge it.

**Comment by allanpilarca** [comment]
Hi @ercanozkaya that was quick :) Tested and working in both frontend and backend :)

**Comment by ercanozkaya** [comment]
Thanks! Merged the branch
