### ISSUE TITLE
Do not call read during cancel action

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#60]
See: https://github.com/joomlatools/textman/pull/215

**Comment by ercanozkaya** [comment]
@jebbdomingo can you check out feature/60-cancel branch, remove the custom override in Textman, and test if lock behavior still works well please?

**Comment by jebbdomingo** [comment]
@ercanozkaya I confirm it works sir 👍

**Comment by ercanozkaya** [comment]
@jebbdomingo Thanks!
