### ISSUE TITLE
Support dot character in MySQL identifier escape

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#61]
See: https://support.joomlatools.com/forums/topic/6927-myslq-error-upgradring-from-3-0-1-to-3-0-2#comment-37620
See: https://support.joomlatools.com/forums/topic/6895

MySQL allows dot character everywhere including database names, columns etc. It also uses dot as a separator between database and table names such as `SELECT * FROM db.table`

KDatabaseAdapterAbstract::quoteIdentifier separates strings on dot and quotes each part separately. Make sure the backticks are properly added when the database or column names have a dot in them.

References:

- http://dev.mysql.com/doc/refman/5.7/en/identifiers.html

**Comment by ercanozkaya** [comment]
@johanjanssens There is no easy way to solve this and we are not receiving anymore reports it seems. Shall we close this for now?

**Comment by johanjanssens** [comment]
@ercanozkaya I agree. Lets mark this as invalid. Too complex too solve.
