### ISSUE TITLE
Remove double scrollbar

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-framework#64]
Remove double scrollbar becuse of overflow: auto on component wrapper. If you want an overflowing wrapper you should use k-flex-wrapper instead

**Comment by robinpoort** [comment]
@ercanozkaya We do not have a floating toolbar on frontend because the `k-ui-container` class is not being added to the `k-ui-namespace` outer div.

Could you make sure that whenever admin.css is being used, the k-ui-container is being added to the div as well?

I pushed a CSS fix in kodekit-ui, joomlatools-ui and joomlatools-framework (all on master) to fix a little CSS double scrollbar bug that appears on frontend editing form when adding the class.

All has been done because of: https://github.com/joomlatools/docman/issues/1070

**Comment by ercanozkaya** [comment]
@robinpoort Fix added to master. Can you test both form views and non-form views in frontend to see if anything breaks?

**Comment by robinpoort** [comment]
@ercanozkaya All should be working as expected now
