### ISSUE TITLE
Use separate folder for reusable components

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#65]
When the framework is installed from a package put the reusable components to the libraries/joomlatools-components folder

**Comment by ercanozkaya** [comment]
@amazeika Can you test this a bit? Two scenarios:

New install: 
* Components should go into libraries/joomlatools-components/ 
* Their assets should go into media/koowa/com_*/
* Database tables should be created for com_files etc.

Existing installs: 
* On upgrade libraries/joomlatools/component/ should only have com_koowa left.
* The rest should go into libraries/joomlatools-components

**Comment by amazeika** [comment]
@ercanozkaya Tested and there are problems:

New Install:

I get an error while installing: Table 'sites_test.j_files_containers' doesn't exist of the following query : SHOW INDEX FROM `j_files_containers`

Funny thing is that the containers table is actually created, so could be a racing condition?

Upgrade:

com_koowa is the only one left on libraries/joomlatools/component/ BUT the other ones are not moved to libraries/joomlatools-components.

**Comment by ercanozkaya** [comment]
@amazeika When did this com_files error occur? In a new install or existing one?

**Comment by amazeika** [comment]
@ercanozkaya All is good with the new package on dropbox. Marking as ready.
