### ISSUE TITLE
Fix path in plugin boostrapping

### ISSUE THREAD

**Issue by allanpilarca** [joomlatools/joomlatools-framework#68]
Need to use JPATH_PLUGINS in https://github.com/joomlatools/joomlatools-framework/blob/master/code/plugins/system/joomlatools/joomlatools.php#L165 to make joomlatools-framework work in joomlatools-platform.

**Comment by johanjanssens** [comment]
@allanpilarca To do that you will need to implement a check to see of you are running in Joomlatools Platform context or in Joomla context and then use the right define.
