### ISSUE TITLE
Joomla 3.7 compatibility

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#69]
Another compatibility issue has arisen in 3.7 beta3. Almost exactly same to the one in #66

**Comment by ercanozkaya** [comment]
@amazeika can you double check the fix please? if no notice is generated on 3.7 it is fine.

**Comment by amazeika** [comment]
@ercanozkaya Just built a dev package and I don't see any notice on frontend forms while using staging branch.

Shall we say all good?

**Comment by ercanozkaya** [comment]
@amazeika Yep that is all good. Thanks!
