### ISSUE TITLE
Use Origin header if Referrer is not present for CSRF checks

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#71]
See: https://support.joomlatools.com/forums/topic/6964
See: https://support.joomlatools.com/forums/topic/7009
See: https://support.joomlatools.com/forums/topic/7038
See: https://support.joomlatools.com/forums/topic/7230
See: https://support.joomlatools.com/forums/topic/6717

If PHP is configured to run byhind a proxy the HTTP_REFERER header might not be available which leads to during POST requests. To reoslve this add HTTP_ORIGIN header to mitigate CSRF attacks.

More info see: https://www.owasp.org/index.php/CSRF_Prevention_Cheat_Sheet#Standard_Header_Checks

- [x] Add KDispatcherRequestInterface::getOrigin
- [x] Check for internal URL in both KDispatcherRequestInterface::getOrigin and KDispatcherRequestInterface::getReferrer
- [x] Remove KFilterInternalUrl since the check is moved into the request object
- [x] Check for referrer and fallback to origin header in CSRF authenticator

**Comment by johanjanssens** [comment]
@ercanozkaya Could we roll this an other bug fixes out in a 3.0.x release?

**Comment by ercanozkaya** [comment]
@johanjanssens We can, it's pending your review
