### ISSUE TITLE
Download issues with sites using Proxies 

### ISSUE THREAD

**Issue by ercanozkaya** [joomlatools/joomlatools-framework#73]
See: joomlatools/docman#929
See: https://support.joomlatools.com/forums/topic/6159-problem-with-pdfs-in-internet-explorer-chrome-and-safari

So far we have multiple customers that are experiencing issues while downloading files while using chrome and IE. The number is likely to grow since the issue is caused by a miss-configuration of the webservers.

**Comment by johanjanssens** [comment]
@ercanozkaya Have you been able to establish this to be a mis-configuration issue of the server? If so what is the exact cause?

**Comment by ercanozkaya** [comment]
@johanjanssens No I haven't. My best guess is the flush() implementation might not be working on some servers under specific conditions.

**Comment by johanjanssens** [comment]
Oki. That could be the case. Something to play around with a bit more.

**Comment by ercanozkaya** [comment]
Setting to ready. *fingers crossed*
