### ISSUE TITLE
Unable to install via composer - package not found [joomlatools/framework:3.*]

### ISSUE THREAD

**Issue by jbear** [joomlatools/joomlatools-framework#8]
joomlatools/framework:3.* is not there

**Comment by johanjanssens** [comment]
Hello! The 3.x release has not been tagged yet, master is being prepped for the a beta release but we haven't done so yet. For the short term we recommend to use the 2.x release, 2.1.6 is the latest one. 

In future for questions, please use our Joomlatools developer chat or forums. Github is only used for the contributing code, if you just have a question [the chat](https://groups.google.com/forum/#!forum/joomlatools-dev) or forum is the preferred channel. Thanks! 

Our contribution guidelines can be found here: https://www.joomlatools.com/developer/contribute/

**Comment by johanjanssens** [comment]
[](url)

**Comment by N6REJ** [comment]
just a FYI that wasn't me that said it johan :dash:

**Comment by johanjanssens** [comment]
Thanks! Sorry about that.
