### ISSUE TITLE
Prepare site UI

### ISSUE THREAD

**Issue by robinpoort** [joomlatools/joomlatools-framework#80]
See: https://github.com/timble/kodekit-ui/issues/15

**Comment by robinpoort** [comment]
@amazeika @ercanozkaya Could you please check out this branch and see if the admin and site UI (in DOCman, FILEman and LOGman) still looks good to you?

I've compared the old and new compiled CSS files and saw only minor differences. Mostly in select2 for the admin UI since I enhanced that in my site UI branch.

If it's looking good we can merge these UI prepare branches so we can easily and safely merge the site UI into master when it's done.

Would be great to get this into the next release of FW so we can get feedback if anything went wrong ;)

**Comment by ercanozkaya** [comment]
All seems okay
