### ISSUE TITLE
Problem with js overrides in templates

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework#84]
See: https://support.joomlatools.com/forums/topic/7480
See: https://support.joomlatools.com/forums/topic/7255

Related to: https://github.com/joomlatools/textman/issues/282

**Comment by johanjanssens** [comment]
@ercanozkaya Another similar issue came in. 

From previous discussions here is how I would try to do this:

I would assume that 'koowa' template is the default, afterall we are in the koowa context. This means setting template is system in 'joomla' very early on.

The condition when we render inside Joomla template is defined by Joomla itself. If we hit the Joomla onBeforeRender event we know that we are still in Joomla context and we need to render in Joomla, in that case we need to set the template to the correct Joomla template. If we didn't hit onBeforeRender we have triggered send earlier on in the cylce ourselves.

There are different ways to let the response layer know we are rendering in Joomla, query variable is one, but it might be better to set state using a header and remove that header in the response. That way we are not polluting the URL and query.

We are going to need to work on this and get it fixed. It also helps us to get rid of the 'koowa' variable in the URL to help us solve: https://github.com/joomlatools/textman/issues/284

**Comment by ercanozkaya** [comment]
@johanjanssens can you review please? Here is how the implementation would look like in Docman:

```

class ComDocmanDispatcherHttp extends ComKoowaDispatcherHttp
{
    protected function _setResponse(KDispatcherContextInterface $context)
    {
        $view   = $context->getRequest()->getQuery()->view;
        $layout = $context->getRequest()->getQuery()->layout;

        if (in_array($view, ['doclink', 'upload']) || ($view === 'files' && $layout === 'select')) {
            $context->getResponse()->getHeaders()->set('X-Response-Send', 1);
        }

        parent::_setResponse($context);
    }
}
```
