### ISSUE TITLE
Properly handle format query parameter when suffix is enabled

### ISSUE THREAD

**Issue by amazeika** [joomlatools/joomlatools-framework#85]
Joomla 3.x does not handle suffixed routes in the same way as 2.5. As a consequence, our json routes which are built as x.raw aren't currently properly parsed by the Joomla router.

EDIT: Problem seems to be back on Joomla 3.7.2.

See:

- https://support.joomlatools.com/forums/topic/7755-upload-url-maybe-wrong-or-does-not-exists#comment-42042

**Comment by amazeika** [comment]
@ercanozkaya Please take a look at this. Some testing would be good.

**Comment by ercanozkaya** [comment]
@amazeika working well on my end. Joomla doesn't care about the suffix at all anymore.

**Comment by amazeika** [comment]
Problem is back on Joomla 3.7.2

**Comment by johanjanssens** [comment]
@amazeika See following: https://support.joomlatools.com/forums/topic/7703 topic too. Problem with ajax calls when suffix is enabled.

**Comment by amazeika** [comment]
@johanjanssens The other issue got solved by updating the htaccess file. Let's see how it goes for this one.

**Comment by amazeika** [comment]
Closing ticket again. Both cases were due to outdated htaccess files.
